name: First workflow
on: push
jobs:
  static_code_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Static code analysis with Lint 
        run: npm run lint
  run_all_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run all tests
        run: npm run test
  build_project:
    runs-on: ubuntu-latest
    needs: run_all_tests
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build project only when all tests passed
        run: npm run build
