name: First workflow as one job
on: push
jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Static code analysis with Lint 
        run: npm run lint
      - name: Run all tests
        run: npm run test
      - name: Build project only when all tests passed
        run: npm run build
