name: Second workflow
on: [issues, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkount source code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Output event details
        run: echo ${{ github }}
